# Generated by Django 3.2.16 on 2022-03-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.ForeignKey(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday')], default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.questionchoices'),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='question',
            field=models.TextField(),
        ),
    ]
