# Generated by Django 3.2.16 on 2022-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20220315_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_two',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='yes'),
        ),
    ]
