# Generated by Django 3.2.16 on 2022-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
