# Generated by Django 3.2.16 on 2022-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_rename_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_four',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_one',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_three',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_two',
            field=models.TextField(),
        ),
    ]
