# Generated by Django 3.2.16 on 2022-12-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20221209_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_two',
        ),
    ]
