# Generated by Django 3.2.16 on 2022-12-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_auto_20221209_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
