# Generated by Django 3.2.16 on 2022-12-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
