# Generated by Django 3.2.16 on 2022-03-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
