# Generated by Django 3.2.16 on 2022-03-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
