# Generated by Django 4.2.1 on 2023-08-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_room_details_created_room_details_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_details',
            old_name='topics',
            new_name='topic',
        ),
    ]
