# Generated by Django 4.2.1 on 2023-08-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0003_rename_topics_room_details_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_details',
            name='message',
        ),
    ]
