# Generated by Django 4.2.1 on 2023-08-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0004_remove_room_details_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_details',
            options={'ordering': ['created']},
        ),
    ]
